  # Title: app-x11vnc-server
  #
  # Author: Luc Rutten
  # Version: 1.0
  # File: tasks/main.yml
  #
  # Description:
  #   Remote support
  #
  # Source:
  #   - http://c-nergy.be/blog/?p=8984

  - name: "check if x11vnc is already installed, if not found skipping...."
    stat:
      path: /usr/bin/x11vnc
    register: x11vnc_active
 
  - name: "Install packages"
    apt:
      name: "{{ item }}"
      update_cache: yes
      state: present
    with_items:
      - x11vnc
    when: x11vnc_active.stat.exists == False

  - name: "Store password"
    shell: "x11vnc -storepasswd {{ vnc_pass }} /etc/x11vnc.pass"

  - name: "Set permissions on /etc/x11vnc.pass"
    file:
     path: /etc/x11vnc.pass
     mode: 0644

  - name: "copy autostart file"
    template:
      src: x11vnc.desktop.j2
      dest: ~/.config/autostart/x11vnc.desktop 
      mode: 0664
    become: false

  - name: "Creates /etc/skel/.config/autostart directory"
    file:
      path: /etc/skel/.config/autostart
      state: directory

  - name: "copy autostart file in skel"
    template:
      src: x11vnc.desktop.j2
      dest: /etc/skel/.config/autostart/x11vnc.desktop 
      mode: 0664

  - name: "Allow traffic on port 5900/tcp"
    ufw:
      rule: allow
      port: 5900
      proto: tcp

  - name: "Blocks x11vnc  in GreenOS Desktop Environment for enduser "
    file:
      path: "/usr/share/applications/x11vnc.desktop"
      mode: 0740
      owner: root
      group: administrator
